services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sre_challenge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    expose:
      - "8000"
    user: "10001:10001"
    environment:
      DATABASE_TYPE: postgres
      DATABASE_LOCATION: postgres://postgres:postgres@postgres:5432/sre_challenge
    depends_on:
      postgres:
        condition: service_healthy

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app
      - grafana
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --no-check-certificate https://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s # Give Nginx a few seconds to parse config and start

  prometheus:
    image: prom/prometheus:v2.45.0
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data: