apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dumbkv-pvc
spec:
  accessModes:
    - ReadWriteMany
  # storageClassName: efs
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi