name: Run Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  validate-k8s-manifests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Scan manifests with kube-linter
        uses: stackrox/kube-linter-action@87802a2f4e01abebb3ee3c67a3002fea71f6eae5 # v1.0.7
        with:
          directory: manifests
      
      - name: Run Kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          args: "-summary -verbose ./manifests"